apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-cloud-application
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-cloud-application
  template:
    metadata:
      labels:
        app: spring-cloud-application
    spec:
      containers:
        - name: spring-cloud-application
          image: docker.io/kavitamil13/spring-cloud-application:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
