apiVersion: v1
kind: Service
metadata:
  name: spring-cloud-application-service
spec:
  type: NodePort
  selector:
    app: spring-cloud-application
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30082
